### PR TITLE
rationals.

### PR DESCRIPTION
**Pull request by LegionMammal978**
resolve the merge conflicts yourself.

### CODE REVIEW

**Comment by vihanb** [comment]
yay finally \o/ \o/ \o/ \o/

**Comment by vihanb** [comment]
these conflicts are gonna be... fun... to resolve :/

**Comment by vihanb** [comment]
;_;

**Comment by LegionMammal978** [comment]
;)

**Comment by vihanb** [comment]
luckily `git merge --rebase` should make this easy.

**Comment by vihanb** [comment]
okay, it wasn't too hard too merge. `git rebase rationals/develop -X ours` solves all conflicts automatically

**Comment by vihanb** [comment]
I ran the tests and there seem to be a bug with `Rational.pow`:

```js
  4 failing

  1) Rational pow should work (instance, ++):

      AssertionError: expected '1' to equal '0'
      + expected - actual

      -1
      +0
      
      at Context.<anonymous> (globals.js:25:42)

  2) Rational pow should work (instance, +-):

      AssertionError: expected '-1' to equal '0'
      + expected - actual

      --1
      +0
      
      at Context.<anonymous> (globals.js:25:42)

  3) Rational pow should work (static, ++):

      AssertionError: expected '1' to equal '0'
      + expected - actual

      -1
      +0
      
      at Context.<anonymous> (globals.js:25:42)

  4) Rational pow should work (static, +-):

      AssertionError: expected '-1' to equal '0'
      + expected - actual

      --1
      +0
      
      at Context.<anonymous> (globals.js:25:42)

```

**Comment by vihanb** [comment]
btw merged it with the latest develop here: e4940dc44971e3ef66edff34b117aef47bb07793 ill merge into develop once tests are fixed (as develop does get deployed live)

**Comment by LegionMammal978** [comment]
You sure that it merges how we want?

**Comment by vihanb** [comment]
@LegionMammal978 hm, lemme take a look. `src/stdlib/ns/Rationals` should of been modified

**Comment by vihanb** [comment]
btw:

```
cheddar> Rational.of(5).pow(-3)
0.008
```

shouldn't it be `1 / 125` rather than `0.08`?

**Comment by vihanb** [comment]
@LegionMammal978 it was because expoentation is not `**` rather than `^`. Fixed it

**Comment by LegionMammal978** [comment]
Why it returned `0.008`:

    export default function pow(num1, den1, num2, den2, cheddar, CheddarRational) {
        // approximate for now, will implement properly later
        return cheddar.init(cheddar.number, 10, 0, Math.pow(num1 / den1, num2 / den2));
    }

**Pull request merged**
