### PR TITLE
feature [cli]: Revamped CLI execution

### PR DESCRIPTION
**Pull request by vihanb**
Major impovement to CLI through `-x` and `cheddar file.cheddar`
execution. Additionally, Cheddar files can now be precompiled
by using the `-o` flag.

### CODE REVIEW

**Comment by schas002** [comment]
> codecov/patch — 0.00% of diff hit (target 1.00%) 

@codecov-io, I object 😦

**Comment by schas002** [comment]
(But Codecov objects :/)

**Comment by vihanb** [comment]
@schas002 I fixed by adding test

**Comment by schas002** [comment]
:ok: then, why Codecov was still objecting?

**Comment by vihanb** [comment]
@schas002 It didn't?

**Pull request merged**
