### PR TITLE
User-defined Classes

### PR DESCRIPTION
**Pull request by vihanb**
This brings classes which with it brings access permissions, op overloading, etc. Casting overloading is not yet supported. Class syntax is not documented thoroughly and secondary constructors are not supported at the moment:

```
class name(private type: name, public type: name) {
    init {
         print "Hi, I'm always run when you initalize this class"
    }

    func myLambda -> self.foo;
    func otherLambda (a, b) -> a + b;
    func bigFunc(a, b) {
        return a + b
    }

    binary op + (a, b) {
        return a + b;
    }
}
```

### CODE REVIEW

**Comment by vihanb** [comment]
Probably won't be merged anytime soon since I have to get tests done.

**Comment by vihanb** [comment]
Though this branch's merging will mark the final release of cheddar v1.0.0!

**Comment by schas002** [comment]
@coveralls :D \o/ thanks 😀

**Comment by schas002** [comment]
The Class feature is merged. Now gimme the v1.0 😜

**Comment by vihanb** [comment]
@schas002 Will prepare right now :D just gotta merge in the feature-op branch and we're good \o/

**Pull request merged**
