### PR TITLE
Basic Rational Functionality 

### PR DESCRIPTION
**Pull request by LegionMammal978**

### CODE REVIEW

**Comment by LegionMammal978** [comment]
The casting test seems to be borked.

**Comment by vihanb** [comment]
Uh oh. Looks like you've run into a cyclic depedency error woth casing ;_; I'll take a look later :/

**Comment by LegionMammal978** [comment]
You might want to write some rational arithmetic/casting tests too, my implementation will probably contain some bugs and I don't have the software to test it myself

**Comment by vihanb** [comment]
I think the problem is that instead of doing for example:

```
import CheddarNumber from '../Number';

export default new Map([
    ['+', (LHS, RHS) => {
        return new CheddarNumber()
    }];
]);
```

what you need to do is move the import _inside_ each function that needs it. (node caches requires so no need to worry about inefficiency). What I mean is, for example, the previous can become:

```
export default new Map([
    ['+', (LHS, RHS) => {
        let CheddarNumber = require('../Number')
        return new CheddarNumber()
    }];
]);
```

This will delay the import, which _should_ solve the cyclic dependency issue

**Comment by vihanb** [comment]
passed! One last thing: can you change the version number in package.json (at root) to 0.2.2?

**Comment by vihanb** [comment]
This drops coverage ~30% which is _a lot_. So I won't merge this now. I'll merge it with develop once I can get tests written up.

**Comment by The-Quill** [comment]
Where does it say 30% @vihanb?

**Comment by vihanb** [comment]
58/78 or somethin I did the math >_>

**Comment by vihanb** [comment]
Nvm it's more like 26%

**Comment by LegionMammal978** [comment]
Yeah, going out of town, won't be able to commit for the next week or so

**Comment by vihanb** [comment]
Ok. Will merge, just add it to the stdlib

**Comment by RikerW** [comment]
0/10 much failing test

**Comment by LegionMammal978** [comment]
So just convert the entire library into an `stdlib` class?

**Comment by vihanb** [comment]
yup, it shouldn't be too hard I have documentation on how in the [development](http://docs.cheddar.vihan.org/api.html) section of the cheddar docs

**Comment by LegionMammal978** [comment]
Nuked the repo, will start a new request

**Comment by vihanb** [comment]
;_; bai rashinl PR

**Pull request closed without merging**
