### PR TITLE
String stdlib

### PR DESCRIPTION
**Pull request by ConorOBrien-Foxx**

### CODE REVIEW

**Comment by schas002** [comment]
Is worse coverage than 11a7eb1 bad? I thought not.

But seems like. :/

**Comment by ConorOBrien-Foxx** [comment]
I should probably find out what coverage is so I can find out what I'm failing -.-

**Comment by schas002** [comment]
> I should probably find out what coverage is so I can find out what I'm failing -.-

This is **test coverage**, a measure of how much code is *actually* tested.

Did you try adding the string stdlib tests?

**Comment by ConorOBrien-Foxx** [comment]
@schas002 I'll have to ask downgoat how to do tests--he's thus far told me not to do them :P

**Comment by ConorOBrien-Foxx** [comment]
oops, wrong place.

**Pull request closed without merging**
