### PR TITLE
C++ Cheddar

### PR DESCRIPTION
**Pull request by vihanb**
This is the small beginning to a significant change to rewrite a significant portion of cheddar's internals in C++.

### CODE REVIEW

**Comment by vihanb** [comment]
This is not my fault stupid istanbul borks code

**Comment by schas002** [comment]
I like the automatic installer. :3

**Comment by vihanb** [comment]
OHMYGODITWORKED

**Comment by vihanb** [comment]
Good news: if someone can test on windows, I can release get cheddar 1.1 out by end of the week (will bring arbitrary precision integers)

**Comment by vihanb** [comment]
The coverage drop may seem bad but remember, we can always blame @LegionMammal978 😜

**Comment by schas002** [comment]
@coveralls which of your posts is the *real* Coveralls? :-S

**Comment by vihanb** [comment]
You know what screw windows, I'm gonna merge anyway once tests pass

**Comment by schas002** [comment]
@vihanb Tests ~~tending to pass~~ passed, ~~well kinda~~..

**Comment by schas002** [comment]
@coveralls O_O

**Pull request merged**
