### PR TITLE
This should fix it

### PR DESCRIPTION
**Pull request by kckennylau**

### CODE REVIEW

**Comment by somebody1234** [comment]
This won't fix it, tail means last `n` chars, what you've changed it to do is make it return all but first `n` chars.

**Comment by kckennylau** [comment]
What about now?

**Comment by somebody1234** [comment]
@kckennylau Now it returns all buut last `n` chars, the original was correct

**Comment by kckennylau** [comment]
I've updated it again.

**Comment by somebody1234** [comment]
Oh yeah it was supposed to be a slice, but the `0,` is unneeded.

**Comment by kckennylau** [comment]
You can delete the `0,` then.

**Pull request merged**
